# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.


## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
import numpy as np

In [2]:
a = np.array([1, 2, 4])    # Create a rank 1 array
print(type(a))             
print(a.shape)
print(a[0], a[1], a[2])

<class 'numpy.ndarray'>
(3,)
1 2 4


In [3]:
# Change element of the array

a[0] = 5
print(a)

[5 2 4]


In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])    # Create a rank 2 array
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


### Create arrays

Numpy also provides many functions to create arrays.

In [6]:
a = np.zeros((2, 2))    # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [8]:
b = np.ones((1, 2))    # Create an array of all ones
print(b)

[[1. 1.]]


In [9]:
c = np.full((2, 2), 7)    # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(2)    # Create a 2x2 identity matrix
print(d)

[[1. 0.]
 [0. 1.]]


In [11]:
e = np.random.random((2, 2))    # Create an array filled with random values
print(e)

[[0.63159684 0.02536298]
 [0.84349395 0.2777368 ]]


### Integer array indexing

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [12]:
a = np.array([[1,2], [3,4], [5,6]])

In [17]:
print(a[[0, 1, 2]])    # Integer array indexing

[[1 2]
 [3 4]
 [5 6]]


In [24]:
array = a[[0, 1, 2], [0, 1, 0]]    # 1° Dimen, 2° Dimen, 3° Dimen
print(array)    

[1 4 5]


In [23]:
array = np.array( [a[0, 0], a[1, 1], a[2, 0]] )
print(array)

[1 4 5]


In [28]:
array = a[[0,0], [1, 1]]    #Reuse the same element from the source array
print(array)

[2 2]


In [29]:
array = np.array( [a[0,1], a[0,1]] )
print(array)

[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [44]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
b = np.array([0, 2, 0, 1])    # Array of indices

print( a[np.arange(4), b] )   # Select one element from each row of a using indices in b

[ 1  6  7 11]


In [43]:
a[np.arange(4), b] += 10    # Mutate one element from each row of a using indices in b
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


### Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [3]:
a = np.array( [[1,2], [3,4], [5,6]] )
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# Find the elementos of a that are biggger than 2
# This returns a numpy array of booleans of the same 
# shape as 'a', where each slot of 'bool_idx' tells
# wheather that element of 'a' is > 2.

bool_idx = (a > 2)    
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [5]:
# We use boolean array indexing to constuct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of 'bool_idx'

print(a[bool_idx])

[3 4 5 6]


In [6]:
# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]


## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [53]:
x = np.array([1., 2.])
print(x.dtype)

float64


In [52]:
x = np.array([1,2])
print(x.dtype)

int32


In [54]:
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64


## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [77]:
x = np.array( [[1,2],[3,4]], dtype=np.float64)
y = np.array( [[5,6],[7,8]], dtype=np.float64)

print(x)
print('')
print(y)

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]


In [61]:
print(x+y)    # Elementwise sum
print('')
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [65]:
print(x-y)    # Elementwise difference (substract)
print('')
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [68]:
print(x*y)    # Elementwise product (multiply)
print('')
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [71]:
print(x / y)    # Elementwise division (divide)
print('')
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [69]:
print(np.sqrt(x))    # Square root

[[1.         1.41421356]
 [1.73205081 2.        ]]


We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [96]:
print('x:',x,sep='\n')
print('y:',y,sep='\n')

x:
[[1. 2.]
 [3. 4.]]
y:
[[5. 6.]
 [7. 8.]]


In [93]:
v = np.array([9, 10])
w = np.array([11,12])

print('v:',v)
print('w:',w)

v: [ 9 10]
w: [11 12]


In [98]:
v.shape
w.shape

(2,)

In [84]:
#Inner product of vectors

print(v.dot(w))
print(np.dot(v, w))

219
219


In [100]:
# Matrix/vector product
# Recuerda, si la segunda componente es I°D, entonces colocarlo vertical

print(x.dot(v))
print('')
print(np.dot(x, v))

[29. 67.]

[29. 67.]


In [107]:
# Pero, qué pasaría si invierto los valores?

print(np.dot(v,x))

[39. 58.]


In [108]:
# Matrix/matrix product

print(x.dot(y))
print('')
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]

[[19. 22.]
 [43. 50.]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [111]:
x = np.array( [[1,2],[3,4]] )

print(np.sum(x))            # Compute the sum of all elements
print(np.sum(x, axis=0))    # Compute sum of each column
print(np.sum(x, axis=1))    # Compute sum of each row

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [113]:
x = np.array( [[1,2],[3,4]] )
print(x)
print('')
print(x.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [115]:
# What happen if we take transpose of a rank 1 array?, It does nothing

y = np.array( [1, 2, 3] )
print(y)
print('')
print(y.T)

[1 2 3]

[1 2 3]


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [116]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array( [[1,2,3],[4,5,6],[7,8,9],[10,11,12]] )
v = np.array( [1,0,1] )
vv = np.tile(v, (4,1))    # stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [120]:
y = x + vv
print('y:\n', y)

y:
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [123]:
print('x:\n',x)
print('')
print('v:\n',v)

x:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

v:
 [1 0 1]


In [126]:
y = v + x
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Extra operations

### arange()

We we use **range** and want to set step = 0.1 there is a problem.

In [8]:
range(1, 9, 0.1)

TypeError: 'float' object cannot be interpreted as an integer

One userful tool is to use **arange()** method.

In [14]:
np.arange(1, 3.1, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])